version: '2'
services:
  ghost:
    restart: always
    image: ghost:0.11.10-alpine
    ports:
      - "2368:2368"
    volumes:
      - .:/var/lib/ghost
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - "MYSQL_PASSWORD=ghost"
  nginx:
    image: nginx:1.13.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/blog.conf
    ports:
      - "8000:80"
    links:
      - "ghost"
  mysql:
    image: mysql:8.0.1
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ghost
      - MYSQL_ROOT_PASSWORD=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost
